server.port=9001

# H2
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.datasource.sql-script-encoding=UTF-8
spring.jpa.defer-datasource-initialization=true

# Actuator
management.endpoints.web.exposure.include=info,health,refresh

# Notre configuration externalisée
mes-configs.limitDeProduits=3
